#!/bin/bash

set -e

cd $(dirname $0)

# Determine the install dir
if [ -z $1 ]; then
    INSTALL_DIR="$HOME/jg_dev_env_clean_build"
else
    INSTALL_DIR=$1
fi

mkdir -p $INSTALL_DIR
echo Install Dir: $INSTALL_DIR

# Build the build environment
cd docker
docker build -f ./centos.dockerfile -t jg-dev-env-build-env:centos ./

# Build the toolset in the build environment
cd ../
docker run -it -v `pwd`:/source -v $INSTALL_DIR:/build_output --entrypoint=/source/docker/build jg-dev-env-build-env:centos

# Hook it up to the users bashrc
# cd $INSTALL_DIR
# ./install
