#!/bin/sh

set -e

export NVM_DIR="$1/apps/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 

nvm install 10.15.2
nvm install 8.15.1
nvm install 6.17.0

# Install libs into each node install
nvm use 10
npm install -g create-react-app express vue eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint

nvm use 8
npm install -g create-react-app express vue eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint

nvm use 6
npm install -g create-react-app express vue eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint
