#!/bin/sh

# Copy to install location

mkdir -p $1/apps/pyenv
cp -rv ./ $1/apps/pyenv

# Make it available
export PYENV_ROOT=$1/apps/pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

# Install python version
pyenv install 3.6.8
pyenv install 2.7.15
