#!/bin/sh

set -e
exit

# Make it available
export PYENV_ROOT=$1/apps/pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

# Install python libs
export PYENV_VERSION=3.7.4
pip install future black pynvim pylint pyflakes pytest python-language-server[all] pyls-mypy
