#!/bin/sh

set -e

export PYENV_ROOT=$1/pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

# Install python libs
export PYENV_VERSION=2.7.15

pip install psutil PyGObject PyGTK 

python ./setup.py install --prefix $1 --exec-prefix $1
