#!/bin/sh

for r in `find . -name .pythonrc`; do
    echo $r
    for p in `cat $r`; do
        echo $p
        export PYTHONPATH=$PYTHONPATH:`pwd`/$p
    done
done

echo $PYTHONPATH

export PYENV_VERSION=3.6.8

nvim

