#!/bin/sh

# Copy to install location
cp -rv ./ $1/pyenv

# Make it available
export PYENV_ROOT=$1/pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

# Install python version
pyenv install 3.6.8
pyenv install 2.7.15

# Install python libs
export PYENV_VERSION=3.6.8
pip install future black pynvim

export PYENV_VERSION=2.7.15
pip install pynvim
