#!/bin/sh

set -e

export PATH=$1/bin:$PATH

curl -fLo $1/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Hook up vim dirs
mkdir -p $1/.vim/plugged
mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.local/share/nvim/site/autoload
ln -f -s $1/.vimrc $HOME/.config/nvim/init.vim
ln -f -s $1/.vim  $HOME/.vim
ln -f -s $1/.local/share/nvim/site/autoload/plug.vim $HOME/.local/share/nvim/site/autoload/plug.vim

# Make pyenv available
export PYENV_ROOT=$1/pyenv/
export PATH=$PYENV_ROOT/bin:$PATH
export PATH=$PYENV_ROOT/shims:$PATH
eval "$(pyenv init -)"

# Install plugins
PYENV_VERSION=3.6.8 nvim +PlugInstall +qa
